on: [push]

jobs:
  build-pdf-job:
    runs-on: ubuntu-latest
    name: 'build-pdf-job'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: 'build-pdf action step'
        id: build-pdf
        uses: ./.github/actions/build-pdf@master
