on: [push]

jobs:
  build-pdf-job:
    runs-on: ubuntu-latest
    name: 'build-pdf-job'
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build-pdf@master
        env:
          DOCKER_BUILDKIT: 1
        working-directory: ./
