on: [push]

jobs:
  build-pdf-job:
    runs-on: ubuntu-latest
    name: 'build-pdf-job'
    steps:
      - uses: actions/checkout@v1

      - uses: ./.github/actions/build-pdf/

      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./test-fused-effects.pdf
          asset_name: test-fused-effects.pdf
          asset_content_type: application/pdf
