on: [push]

jobs:
  build-pdf-job:
    runs-on: ubuntu-latest
    name: 'build-pdf-job'
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v1
      - run: |
          cp -a ./* ./.github/actions/build-pdf/
      - uses: ./.github/actions/build-pdf/
        env:
          DOCKER_BUILDKIT: 1
